### ISSUE TITLE
Upgrade to messageformat@4.0.0-8

### ISSUE THREAD

**Issue by catamorphism** [lucacasonato/messageformat.dev#9]
See https://github.com/messageformat/messageformat/releases/tag/messageformat%404.0.0-8

This is not a straightforward change, as it will break some of the examples in the docs, most notably due to the "matching on variables instead of expressions" change.

**Comment by lucacasonato** [comment]
Updated the docs in https://github.com/lucacasonato/messageformat.dev/commit/4ceb3c69b7ddf6a1bbd6cd5b70d86edfb2f5a248
